### ISSUE TITLE
MMS (Picture and Video Messaging Problem)

### ISSUE THREAD

**Issue by ExtremeFiretop** [Android-L-Porting-Team/Android-L-Mako#13]
I was able to send one picture message to a buddie. 

When he apparently send me the middle finger back in a picture. I was never able to download it. I have made sure to have the correct APN settings in both the system and in hangouts. Nothing seems to change it. Data works fine, I can browse without issue using 3G.

Seems to be specific with MMS messages. Worked fine in KitKat 4.4.4

**Comment by Dpat09** [comment]
This is a known L preview issue that has been acknowledged in the official L preview tracker, unfortunately the only work around seems to be to turn off WiFi to recieve the mms. I have a Nexus 5 and have been actively involved in the issue tracker myself. This is not Nexus 4 specific. If someone can upgrade my permissions for this project please do so. I can help clear out these issues posted because I know if they are L specific rather than device/ROM problem.

**Comment by Dpat09** [comment]
https://code.google.com/p/android-developer-preview/issues/detail?id=52

**Comment by percy-g2** [comment]
thank you Dpat09 for explaination
