### ISSUE TITLE
Camera graphical glitch

### ISSUE THREAD

**Issue by ConnorBaker** [Android-L-Porting-Team/Android-L-Mako#17]
This one may be an issue on Google's side.
Notice the camera pinwheel in the top left hand corner? This occurs on every launch of the camera (without it being stored in the RAM). It goes away after taking a picture.
![screenshot_2014-07-08-01-59-56](https://cloud.githubusercontent.com/assets/3880346/3505735/6833a540-0665-11e4-98e5-154905cd63df.png)

Warm regards,
Connor Baker

**Comment by Darex2094** [comment]
I pulled up my own camera on Beta 2 and I'm under the impression what we're seeing is expected behavior, is it not? I get that with Google Camera on 4.4.3 as well.
![screenshot_2014-07-08-08-51-08](https://cloud.githubusercontent.com/assets/8104260/3512302/fc6434a8-06b7-11e4-9d89-839d84704188.png)

**Comment by percy-g2** [comment]
It's called preview for a reason

**Comment by Darex2094** [comment]
With that being the closing reason to a bug report I'm surprised we aren't closing everything with the same response: It's called preview for a reason. 

Why even run a bug tracker?

**Comment by percy-g2** [comment]
https://code.google.com/p/android-developer-preview/issues/list

**Comment by Darex2094** [comment]
Yes, I see, know of, and have regularly cited the official bug tracker. Can you link the upstream bug report related to this issue? I can't seem to find it.

In spirit of the purpose of what this project represents and what this bug tracker is here to do (be a sounding board for people to post bugs they find, credible or not), it may be prudent to link the closed bug to something worth reading instead of a blanket statement and blanket link. Otherwise you can close all the bugs as 'it's a preview thing'

**Comment by percy-g2** [comment]
https://code.google.com/p/android-developer-preview/issues/detail?id=210&can=1&colspec=ID%20Type%20Status%20Owner%20Summary&start=200

**Comment by Darex2094** [comment]
Thank you for taking the time to post the relevant linked information.

**Comment by percy-g2** [comment]
Next time use search button and don't report bug's which are generic to L preview .Device related bug's will be resolved and accepted not L preview .
