### ISSUE TITLE
camera problem in beta 3 rev 5

### ISSUE THREAD

**Issue by anujthapar** [Android-L-Porting-Team/Android-L-Mako#82]
i used beta 3 rev 5 where after one or two shots in official or another camera software is hanging after which it fails to recognise camera.

**Comment by anujthapar** [comment]
If u made such problem removed i can migrate to beta 4

**Comment by eric10234** [comment]
I think this problem is due to the NuPlayer being selected as the default player under developer settings.

Quote: "For all camera issues please try this: go to the Dev settings and disable nuplayer! I'm posting it again because I think it will be lost in all the posts! If it works hopefully the contributing devs will catch it and put it in the main post"
http://forum.xda-developers.com/nexus-4/development/lpv-79-mako-port-beta-t2807446

If you have already disabled NuPlayer, disregard this comment.

**Comment by anujthapar** [comment]
Thanks

**Comment by karishnu** [comment]
Pls close this issue .. It has been fixed
