### ISSUE TITLE
Camera bug

### ISSUE THREAD

**Issue by luis1997** [Android-L-Porting-Team/Android-L-Mako#87]
Beta 4 just having troubles with camera it doesnt shot and when do it CRASHES, and later doesnt  open The app....

**Comment by ruikaka16** [comment]
I faced the same issue,but after reboot the system,it have fixed,

**Comment by luis1997** [comment]
Yes but still doesnt shot, i cant take pictures and lateral cannot connect

**Comment by nox-321** [comment]
Did you clean flashed ?

**Comment by luis1997** [comment]
yes i did

**Comment by nox-321** [comment]
Check if "Use NuPlayer" is ticked in developper options. If so, untick and it should be OK.

**Comment by luis1997** [comment]
it was ticked, so im rebooting....

**Comment by luis1997** [comment]
fixed, THANKS! but in beta3 pre5 it was ticked on and i never had problems with camera.... maybe it some of the new kernel... right?

**Comment by nox-321** [comment]
Dunno. The devs pinned on XDA " For all camera issues please try this: go to the Dev settings and disable nuplayer! I'm posting it again because I think it will be lost in all the posts! If it works hopefully the contributing devs will catch it and put it in the main post". I think you can close bug.

**Comment by luis1997** [comment]
yes it was lost, well thanks!
